---
language: python

dist: xenial

sudo: true

python:
  - "3.6"
  - "3.7"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: nightly

install:
  - pip install --process-dependency-links .[dev]
  - pip install codacy-coverage
  - pip install pytest-cov

script:
  - pytest --cov caroline

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
